/**
 * Wraps a successful payload in the standard API envelope.
 */
export function formatSuccess(data) {
  return {
    success: true,
    data,
    timestamp: new Date().toISOString(),
  };
}

/**
 * Wraps an error message in the standard API envelope.
 */
export function formatError(message) {
  return {
    success: false,
    error: message,
    timestamp: new Date().toISOString(),
  };
}

/**
 * Returns a graceful fallback response when Gemini is unavailable.
 * HTTP status stays 200 so Axios does not throw — the frontend
 * detects the `fallback: true` flag and renders the fallback UI.
 *
 * @param {'GEMINI_QUOTA_EXCEEDED'|'GEMINI_ERROR'} errorType
 * @param {string} message  - User-facing friendly message (no raw error text)
 * @param {Object} fallbackRecommendation - Generated by fallbackRecommendationService
 */
export function formatFallback(errorType, message, fallbackRecommendation) {
  return {
    success: false,
    fallback: true,
    errorType,
    message,
    fallbackRecommendation,
    timestamp: new Date().toISOString(),
  };
}
