import { useState, useEffect } from 'react';
import {
  LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid,
  PieChart, Pie, Cell, BarChart, Bar,
} from 'recharts';
import LoadingSpinner from '../components/LoadingSpinner.jsx';
import ErrorBanner    from '../components/ErrorBanner.jsx';
import MetricCard     from '../components/MetricCard.jsx';
import SectionCard    from '../components/SectionCard.jsx';
import ChartCard      from '../components/ChartCard.jsx';
import { useLanguage } from '../context/LanguageContext.jsx';
import { getWeeklyReport } from '../api/reportApi.js';

export default function ReportsPage() {
  const { t }                = useLanguage();
  const [report, setReport]  = useState(null);
  const [loading, setLoad]   = useState(true);
  const [error, setError]    = useState(null);
  const [pdfState, setPdf]   = useState('idle');

  useEffect(() => {
    getWeeklyReport()
      .then(r => setReport(r.data.data))
      .catch(() => setError('Cannot reach backend.'))
      .finally(() => setLoad(false));
  }, []);

  if (loading) return <LoadingSpinner message="Loading weekly report…" />;
  if (error)   return <ErrorBanner message={error} />;

  const r = report;

  function handleDownloadPDF() {
    setPdf('loading');
    setTimeout(() => setPdf('done'), 2000);
    setTimeout(() => setPdf('idle'), 5000);
  }

  return (
    <div className="space-y-5">

      {/* Report header */}
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-5">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="text-xs font-semibold text-cyan-400 uppercase tracking-wide mb-1">
              {t('weeklyAIReport')}
            </p>
            <h1 className="text-xl font-bold text-slate-100">
              Week {r.period.weekNumber}, {r.period.year}
            </h1>
            <p className="text-sm text-slate-400 mt-1">{r.period.start} → {r.period.end}</p>
            <p className="text-xs text-slate-600 mt-1">Generated by {r.generatedBy}</p>
          </div>
          <button onClick={handleDownloadPDF}
            disabled={pdfState === 'loading'}
            className="shrink-0 px-4 py-2 rounded-lg bg-gradient-to-r from-cyan-600 to-purple-600
                       text-white text-sm font-semibold hover:from-cyan-500 hover:to-purple-500
                       transition-all disabled:opacity-50 disabled:cursor-not-allowed">
            {pdfState === 'loading' ? t('generatingPDF') : pdfState === 'done' ? t('pdfReady') : t('downloadPDF')}
          </button>
        </div>
        {pdfState === 'done' && (
          <p className="text-xs text-amber-400 mt-3">
            {t('pdfMockNote')}
          </p>
        )}
      </div>

      {/* Executive Summary */}
      <SectionCard title={t('executiveSummary')} description={t('aiGeneratedOverview')}>
        <p className="text-sm text-slate-300 leading-relaxed">{r.executiveSummary}</p>
      </SectionCard>

      {/* Financial KPIs */}
      <div className="grid grid-cols-2 xl:grid-cols-4 gap-3">
        <MetricCard title={t('totalRevenue')}       value={`₺${(r.financialSummary.totalRevenue7d/1000).toFixed(0)}K`}  description={`${r.financialSummary.revenueChange > 0 ? '+' : ''}${r.financialSummary.revenueChange}% vs prev week`} color="cyan"  icon="💰" />
        <MetricCard title={t('revenueAtRisk')}     value={`₺${(r.financialSummary.revenueAtRisk/1000).toFixed(0)}K`}   description="From stockouts & supply chain" color="red"   icon="💸" />
        <MetricCard title={t('revenueOpportunity')} value={`₺${(r.financialSummary.revenueOpportunity/1000).toFixed(0)}K`} description="If AI actions executed"  color="green" icon="🎯" />
        <MetricCard title={t('portfolioROI')}      value={`${r.financialSummary.portfolioROIIfActionsExecuted}%`}      description={t('withAllRecs')}        color="green" icon="📈" />
      </div>

      {/* Charts row */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-5">
        <ChartCard title={t('weeklyRevTrend')} description={t('dailyVsTarget')} className="xl:col-span-2">
          <ResponsiveContainer width="100%" height={200}>
            <LineChart data={r.weeklyRevenueTrend}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis dataKey="day" stroke="#475569" tick={{ fontSize: 11 }} />
              <YAxis stroke="#475569" tick={{ fontSize: 11 }} tickFormatter={v => `₺${(v/1000).toFixed(0)}K`} />
              <Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #1e293b', borderRadius: '8px', fontSize: '12px' }}
                formatter={v => [`₺${v.toLocaleString()}`, '']} />
              <Line type="monotone" dataKey="revenue" name="Revenue" stroke="#06b6d4" strokeWidth={2} dot={{ r: 3, fill: '#06b6d4' }} />
              <Line type="monotone" dataKey="target" name="Target" stroke="#475569" strokeWidth={1.5} strokeDasharray="4 4" dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title={t('roiProjection')} description={t('currentVsAI')}>
          <ResponsiveContainer width="100%" height={200}>
            <LineChart data={r.roiProjection}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis dataKey="month" stroke="#475569" tick={{ fontSize: 10 }} />
              <YAxis stroke="#475569" tick={{ fontSize: 10 }} tickFormatter={v => `${v}%`} />
              <Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #1e293b', borderRadius: '8px', fontSize: '12px' }}
                formatter={v => [`${v}%`, '']} />
              <Line type="monotone" dataKey="withActions" name="With AI Actions" stroke="#10b981" strokeWidth={2} dot={{ r: 3 }} />
              <Line type="monotone" dataKey="current" name="Current Path" stroke="#f59e0b" strokeWidth={1.5} strokeDasharray="4 4" dot={false} />
              <Line type="monotone" dataKey="market" name="Market Avg" stroke="#475569" strokeWidth={1} strokeDasharray="2 4" dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      {/* Risk + Opportunity dist */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-5">
        <ChartCard title={t('riskDistribution')} description={t('byRiskCategory')}>
          <div className="flex items-center gap-4">
            <ResponsiveContainer width="40%" height={160}>
              <PieChart>
                <Pie data={r.riskDistribution} cx="50%" cy="50%" outerRadius={65} dataKey="value">
                  {r.riskDistribution.map((d, i) => <Cell key={i} fill={d.color} />)}
                </Pie>
              </PieChart>
            </ResponsiveContainer>
            <div className="flex-1 space-y-2">
              {r.riskDistribution.map(d => (
                <div key={d.name} className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="h-2.5 w-2.5 rounded-full shrink-0" style={{ background: d.color }} />
                    <span className="text-xs text-slate-400">{d.name}</span>
                  </div>
                  <span className="text-xs font-bold text-slate-200">{d.value}%</span>
                </div>
              ))}
            </div>
          </div>
        </ChartCard>

        <ChartCard title={t('oppDistribution')} description={t('byOppType')}>
          <div className="flex items-center gap-4">
            <ResponsiveContainer width="40%" height={160}>
              <PieChart>
                <Pie data={r.opportunityDistribution} cx="50%" cy="50%" outerRadius={65} dataKey="value">
                  {r.opportunityDistribution.map((d, i) => <Cell key={i} fill={d.color} />)}
                </Pie>
              </PieChart>
            </ResponsiveContainer>
            <div className="flex-1 space-y-2">
              {r.opportunityDistribution.map(d => (
                <div key={d.name} className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="h-2.5 w-2.5 rounded-full shrink-0" style={{ background: d.color }} />
                    <span className="text-xs text-slate-400">{d.name}</span>
                  </div>
                  <span className="text-xs font-bold text-slate-200">{d.value}%</span>
                </div>
              ))}
            </div>
          </div>
        </ChartCard>
      </div>

      {/* Top Risks & Opportunities */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-5">
        <SectionCard title={t('top5Risks')} description={t('rankedByUrgency')} padding={false}>
          <div className="divide-y divide-slate-800">
            {r.topRisks.map(risk => (
              <div key={risk.rank} className="px-4 py-3 flex items-start gap-3">
                <span className={`shrink-0 text-xs font-bold w-5 mt-0.5 ${risk.urgency === 'critical' ? 'text-red-400' : risk.urgency === 'high' ? 'text-amber-400' : 'text-slate-500'}`}>
                  #{risk.rank}
                </span>
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-semibold text-slate-200">{risk.title}</p>
                  <p className="text-xs text-slate-500">{risk.category} · {risk.impact}</p>
                  <p className="text-xs text-cyan-400 mt-0.5">→ {risk.action}</p>
                </div>
              </div>
            ))}
          </div>
        </SectionCard>

        <SectionCard title={t('top5Ops')} description={t('rankedByValue')} padding={false}>
          <div className="divide-y divide-slate-800">
            {r.topOpportunities.map(opp => (
              <div key={opp.rank} className="px-4 py-3 flex items-start gap-3">
                <span className="shrink-0 text-xs font-bold text-green-400 w-5 mt-0.5">#{opp.rank}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-semibold text-slate-200">{opp.title}</p>
                  <p className="text-xs text-slate-500">{opp.category} · {opp.expectedValue}</p>
                  <p className="text-xs text-green-400 mt-0.5">→ {opp.action}</p>
                </div>
                <span className="shrink-0 text-xs text-slate-500">{opp.confidence}%</span>
              </div>
            ))}
          </div>
        </SectionCard>
      </div>

      {/* Recommended Actions */}
      <SectionCard title={t('recommendedActions')} description="Prioritized AI action plan for this week" padding={false}>
        <div className="divide-y divide-slate-800">
          {r.recommendedActions.map(action => (
            <div key={action.priority} className="px-4 py-3 flex items-center gap-3">
              <div className={`h-6 w-6 rounded-full flex items-center justify-center shrink-0 ${
                action.priority <= 2 ? 'bg-red-500/20 text-red-400' : action.priority === 3 ? 'bg-amber-500/20 text-amber-400' : 'bg-slate-700 text-slate-400'
              } text-xs font-bold`}>
                {action.priority}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-semibold text-slate-200">{action.action}</p>
                <p className="text-xs text-slate-600">Deadline: {action.deadline}</p>
              </div>
              {action.expectedROI && (
                <span className="shrink-0 text-xs font-bold text-green-400">{action.expectedROI}% ROI</span>
              )}
              <span className={`shrink-0 text-xs px-2 py-0.5 rounded-full border ${
                action.status === 'pending' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' : 'bg-green-500/10 text-green-400 border-green-500/20'
              }`}>
                {action.status}
              </span>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* Summary sections */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
        {[
          {
            title: 'Trend Summary', icon: '📡', color: 'border-l-cyan-500',
            items: [
              `${r.trendSummary.totalTrendSignals} trend signals active`,
              `${r.trendSummary.highMomentumSignals} high-momentum signals`,
              `Top: ${r.trendSummary.topOpportunity.product}`,
              `+${r.trendSummary.topOpportunity.trendChange}% demand in ${r.trendSummary.topOpportunity.timeWindow}`,
            ],
          },
          {
            title: 'Inventory Summary', icon: '📦', color: 'border-l-amber-500',
            items: [
              `${r.inventorySummary.criticalStockout} critical stockouts`,
              `${r.inventorySummary.highRisk} high-risk products`,
              `Avg ${r.inventorySummary.avgDaysUntilStockout.toFixed(1)} days remaining`,
              `₺${(r.inventorySummary.totalReorderValue/1000).toFixed(0)}K reorder needed`,
            ],
          },
          {
            title: 'Pricing Summary', icon: '💹', color: 'border-l-green-500',
            items: [
              `${r.pricingSummary.totalRecommendations} recommendations`,
              `${r.pricingSummary.increaseRecommendations} price increases`,
              `${r.pricingSummary.decreaseRecommendations} price decreases`,
              `₺${(r.pricingSummary.potentialRevenueImpact/1000).toFixed(0)}K total impact`,
            ],
          },
          {
            title: 'Fintech Summary', icon: '💳', color: 'border-l-purple-500',
            items: [
              `${r.fintechSummary.totalOffers} financing offers`,
              `₺${(r.fintechSummary.totalAvailableCapital/1000).toFixed(0)}K total capital`,
              `${r.fintechSummary.avgEstimatedROI}% avg expected ROI`,
              `₺${(r.fintechSummary.topOffer.amount/1000).toFixed(0)}K top offer`,
            ],
          },
        ].map(({ title, icon, color, items }) => (
          <div key={title} className={`rounded-xl border border-slate-800 border-l-4 ${color} bg-slate-900 p-4`}>
            <div className="flex items-center gap-2 mb-3">
              <span className="text-lg">{icon}</span>
              <p className="text-sm font-semibold text-slate-200">{title}</p>
            </div>
            <ul className="space-y-1.5">
              {items.map((item, i) => (
                <li key={i} className="text-xs text-slate-400 flex items-start gap-1.5">
                  <span className="text-slate-600 shrink-0">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
}
